[package]
name = "bshook_il2cpp"
version = "0.1.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"

[dependencies]
dlopen = "0.1"
dlopen_derive = "0.1"
lazy_static = "1.4"
thiserror = "1.0"
